[build]
builder = "nixpacks"
buildCommand = "yarn build:embed && yarn build"

[build.env]
NEXT_PUBLIC_HOST_SERVICE_URL = "$NEXT_PUBLIC_HOST_SERVICE_URL"
NEXT_PUBLIC_CURIA_FORUM_URL = "$NEXT_PUBLIC_CURIA_FORUM_URL"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
SERVICE_NAME = "curia-host-service"

# These will need to be set in Railway dashboard
# DATABASE_URL = ""
# JWT_SECRET = ""
# CURIA_PRIVATE_KEY = ""
# CURIA_PUBLIC_KEY = ""
# CURIA_KEY_ID = ""

# Embed system environment variables (CRITICAL for production)
# NEXT_PUBLIC_HOST_SERVICE_URL = "https://your-host-service.railway.app"
# NEXT_PUBLIC_CURIA_FORUM_URL = "https://your-main-forum.railway.app" 